In [11]:
# pandas for data manipulation and analysis
import pandas as pd
# matplotlib for data visualization
import matplotlib.pyplot as plt
# train_test_split for splitting the data into training and testing sets
from sklearn.model_selection import train_test_split
# DecisionTreeClassifier for decision tree classification
from sklearn.tree import DecisionTreeClassifier
# accuracy_score for evaluating the model
from sklearn.metrics import accuracy_score

In [12]:
# Load the diabetes dataset using pandas or from sklearn datasets
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']
# load dataset; the CSV already contains a header row, so we keep it as the column names
# and avoid converting the string header values like 'Pregnancies' into numeric data
# for the model.
diabetes_df = pd.read_csv("diabetes.csv", header=0, names=col_names)
# Display the first 5 rows of the DataFrame
diabetes_df.head(5)

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         6      148  72    35        0  33.6     0.627   50      1
1         1       85  66    29        0  26.6     0.351   31      0
2         8      183  64     0        0  23.3     0.672   32      1
3         1       89  66    23       94  28.1     0.167   21      0
4         0      137  40    35      168  43.1     2.288   33      1

In [13]:
#Display the first 5 rows of the dataframe
diabetes_df.head(5)

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         6      148  72    35        0  33.6     0.627   50      1
1         1       85  66    29        0  26.6     0.351   31      0
2         8      183  64     0        0  23.3     0.672   32      1
3         1       89  66    23       94  28.1     0.167   21      0
4         0      137  40    35      168  43.1     2.288   33      1

In [14]:
#Display the data types of each column.
diabetes_df.dtypes

pregnant      int64
glucose       int64
bp            int64
skin          int64
insulin       int64
bmi         float64
pedigree    float64
age           int64
label         int64
dtype: object

In [15]:
#Display the number of missing values in each column
diabetes_df.isnull().sum()

pregnant    0
glucose     0
bp          0
skin        0
insulin     0
bmi         0
pedigree    0
age         0
label       0
dtype: int64

In [16]:
#Display the number of unique values in each column
diabetes_df.nunique()

pregnant     17
glucose     136
bp           47
skin         51
insulin     186
bmi         248
pedigree    517
age          52
label         2
dtype: int64

In [17]:
#Display the summary statistics of the dataframe.
diabetes_df.describe()

,pregnant,glucose,bp,skin,insulin,bmi,pedigree,age,label
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [18]:
#split dataset in features and target variable
feature_cols = ['pregnant', 'insulin', 'bmi', 'age','glucose','bp','pedigree']
X = diabetes_df[feature_cols] # Features
y = diabetes_df.label # Target variable

In [19]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% testing

In [20]:
# Building Decision Tree Model
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()
# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [21]:
# Model Accuracy, how often is the classifier correct?
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6796536796536796